spring:
  config:
    activate:
      on-profile: mock
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  flyway:
    enabled: false
  sql:
    init:
      mode: never

feature:
  ai-budget-enabled: true

data-source-mode: mock

app:
  aiBudget:
    mockEnabled: true