spring:
  config:
    activate:
      on-profile: plaid
  datasource:
    url: jdbc:postgresql://localhost:5432/sand_dollar
    username: sand_dollar_user
    password: sand_dollar_password
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  sql:
    init:
      mode: never

feature:
  ai-budget-enabled: true

data-source-mode: plaid

plaid:
  client-id: ${PLAID_CLIENT_ID}
  secret: ${PLAID_SECRET}
  environment: ${PLAID_ENV:development}
  webhook-url: ${PLAID_WEBHOOK_URL:http://localhost:8080/api/plaid/webhook}
  redirect-uri: ${PLAID_REDIRECT_URI:}

app:
  origin: ${APP_ORIGIN:http://localhost:5173}
  dev-auth-header: ${DEV_AUTH_HEADER:letmein}
  aiBudget:
    mockEnabled: false

openai:
  api-key: ${OPENAI_API_KEY}
  model: ${OPENAI_MODEL:gpt-4o-mini}
