spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/sand_dollar
    username: sand_dollar_user
    password: sand_dollar_password
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  sql:
    init:
      mode: never

cors:
  allowed-origins: "http://localhost:5177,http://localhost:5173,https://sanddollar.ngrok.app"

feature:
  ai-budget-enabled: true

data-source-mode: plaid

app:
  aiBudget:
    mockEnabled: false
