spring:
  application:
    name: sand-dollar
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/sand_dollar}
    username: ${DB_USERNAME:sand_dollar_user}
    password: ${DB_PASSWORD:sand_dollar_password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      enabled: false

logging:
  level:
    com.sanddollar: DEBUG
    org.springframework.security: DEBUG
    
jwt:
  secret: ${JWT_SECRET:default-secret-key-change-this-in-production}
  expiration: ${JWT_EXPIRATION_MS:900000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_MS:2592000000}

encryption:
  key: ${ENCRYPTION_KEY:}

plaid:
  client-id: ${PLAID_CLIENT_ID:}
  secret: ${PLAID_SECRET:}
  environment: ${PLAID_ENV:sandbox}
  redirect-uri: ${PLAID_REDIRECT_URI:}

openai:
  api-key: ${OPENAI_API_KEY:dummy-key}
  api.key: ${OPENAI_API_KEY:dummy-key}
  model: ${OPENAI_MODEL:gpt-4o-mini}
  max-tokens: ${OPENAI_MAX_TOKENS:2000}
  temperature: ${OPENAI_TEMPERATURE:0.3}
  connect-timeout-ms: ${OPENAI_CONNECT_TIMEOUT_MS:15000}
  read-timeout-ms: ${OPENAI_READ_TIMEOUT_MS:20000}
  max-retries: ${OPENAI_MAX_RETRIES:2}

cors:
  allowed-origins: "http://localhost:5173,http://localhost:5177,https://49f0aaad8ac3.ngrok-free.app"

refresh-token:
  secret: ${REFRESH_TOKEN_SECRET:default-refresh-secret-change-this}

dev:
  auth-header: ${DEV_AUTH_HEADER:letmein}

# Data Source Configuration
data-source-mode: ${DATA_SOURCE_MODE:mock}

feature:
  ai-budget-enabled: ${AI_BUDGET_ENABLED:true}
  ai-budget:
    rate-limit-per-minute: ${AI_BUDGET_RATE_LIMIT_PER_MINUTE:5}

server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    max-swallow-size: 1MB
    max-http-form-post-size: 1048576
    max-http-header-size: 16834

---
spring:
  config:
    activate:
      on-profile: docker
      
  datasource:
    url: jdbc:postgresql://postgres:5432/sand_dollar
