spring:
  application:
    name: sand-dollar
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/sand_dollar}
    username: ${DB_USERNAME:sand_dollar_user}
    password: ${DB_PASSWORD:sand_dollar_password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.sanddollar: DEBUG
    org.springframework.security: DEBUG
    
jwt:
  secret: ${JWT_SECRET:default-secret-key-change-this-in-production}
  expiration: ${JWT_EXPIRATION_MS:900000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION_MS:2592000000}

encryption:
  key: ${ENCRYPTION_KEY:}

plaid:
  client-id: ${PLAID_CLIENT_ID:}
  secret: ${PLAID_SECRET:}

openai:
  api-key: ${OPENAI_API_KEY:}
  model: ${OPENAI_MODEL:gpt-4o-mini}
  max-tokens: ${OPENAI_MAX_TOKENS:2000}
  temperature: ${OPENAI_TEMPERATURE:0.3}

cors:
  allowed-origins: ${APP_ORIGIN:http://localhost:5173}

refresh-token:
  secret: ${REFRESH_TOKEN_SECRET:default-refresh-secret-change-this}

dev:
  auth-header: ${DEV_AUTH_HEADER:letmein}

# Data Source Configuration
data-source-mode: ${DATA_SOURCE_MODE:mock}

---
spring:
  config:
    activate:
      on-profile: docker
      
  datasource:
    url: jdbc:postgresql://postgres:5432/sand_dollar